name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.3', '8.4', '8.5']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer install
        run: composer install --no-progress --no-ansi --prefer-dist

      - name: PHP CodeSniffer
        run: composer phpcs

      - name: PHPStan
        run: composer phpstan

      - name: Run tests
        run: composer test